"""Archive RNA-seq addenda into rnaseq_summary.json (ADDENDA-001).

Script 11 writes the base summary; R2 (AUC points) and S1 (PAM50 block) were
archived by verified one-off computations. This script makes those addenda
regenerable: it recomputes them deterministically from committed artifacts and
merges them into rnaseq_summary.json.

Rules (reverse-engineered from committed values, verified this round):
  AUC3_point/AUC5_point = round(midpoint of AUC CI, 2)
  PAM50 per stratum: n/deaths ints, HR/CI round(x,3), p round(p,4)
Contract: byte-identical to committed file, else exit nonzero.
Run order: after scripts/11_rnaseq_validate.py.
"""
import json
import pandas as pd
import numpy as np
from statsmodels.duration.hazard_regression import PHReg

RAW = "results/raw/"


def log(m):
    print(m, flush=True)
    with open("logs/archive_addenda.log", "a") as f:
        f.write(m + "\n")


d = json.load(open(RAW + "rnaseq_summary.json"))
d["AUC3_point"] = round(sum(d["AUC3_CI"]) / 2, 2)
d["AUC5_point"] = round(sum(d["AUC5_CI"]) / 2, 2)
r = pd.read_csv(RAW + "rnaseq_risk_GSE96058.tsv", sep="\t")
pam = {}
for st in ["Basal", "Her2", "LumA", "LumB", "Normal"]:
    s = r[r.pam50_subtype == st]
    sd = s.risk.std()
    f = PHReg(s.OS_years.values, (s.risk.values / sd).reshape(-1, 1), s.OS_event.values).fit(disp=0)
    hr = float(np.exp(f.params[0]))
    lo = float(np.exp(f.params[0] - 1.96 * f.bse[0]))
    hi = float(np.exp(f.params[0] + 1.96 * f.bse[0]))
    pam[st] = {"n": int(len(s)), "deaths": int(s.OS_event.sum()),
               "HR": round(hr, 3), "CI": [round(lo, 3), round(hi, 3)],
               "p": round(float(f.pvalues[0]), 4)}
d["PAM50"] = pam
text = json.dumps(d, indent=2)
old = open(RAW + "rnaseq_summary.json").read()
import os
# compare against committed bytes: regenerate-then-compare needs committed copy
ref = os.popen("git show HEAD:results/raw/rnaseq_summary.json").read()
if text != ref:
    open("/tmp/addenda_new.json", "w").write(text)
    raise SystemExit("MISMATCH: regenerated addenda != committed rnaseq_summary.json (see /tmp/addenda_new.json)")
open(RAW + "rnaseq_summary.json", "w").write(text)
log("ADDENDA-001: AUC points + PAM50 block regenerated byte-identical; PASS")
